/**
 * Database Migration & Synchronization Utility for WoundCarePro
 * 
 * Converts the decrypted JSON database (database.json / wound-care-local-db.json)
 * into standard SQL INSERT statements for MariaDB/MySQL.
 * Output file can be directly imported into local Docker MariaDB or DS224+ MariaDB.
 * 
 * Usage:
 *   node migrate.js [path/to/decrypted_db.json]
 */

const fs = require('fs');
const path = require('path');

// Helper to escape values for SQL
const sqlVal = (val) => {
  if (val === null || val === undefined || val === '') return 'NULL';
  if (typeof val === 'number') return val;
  if (typeof val === 'boolean') return val ? 1 : 0;
  
  // Standard SQL escape quotes
  const escaped = String(val).replace(/'/g, "''");
  return `'${escaped}'`;
};

// Convert ISO string to MySQL local TIMESTAMP format
const sqlDate = (isoStr) => {
  if (!isoStr) return 'CURRENT_TIMESTAMP';
  try {
    const d = new Date(isoStr);
    if (isNaN(d.getTime())) return 'CURRENT_TIMESTAMP';
    return `'${d.toISOString().slice(0, 19).replace('T', ' ')}'`;
  } catch (e) {
    return 'CURRENT_TIMESTAMP';
  }
};

const runMigration = () => {
  // Determine input path
  const args = process.argv.slice(2);
  const inputFilePath = args[0] || path.join(__dirname, '..', 'wound-care-local-db.json');
  const outputFilePath = path.join(__dirname, 'import.sql');

  console.log(`\x1b[36m=== WoundCarePro SQL Exporter ===\x1b[0m`);
  console.log(`Reading JSON database from: ${inputFilePath}`);

  if (!fs.existsSync(inputFilePath)) {
    console.error(`\x1b[31mError: Input file not found! Input path: ${inputFilePath}\x1b[0m`);
    console.log(`\nUsage hint:`);
    console.log(`Provide the decrypted database file, e.g. from the 'Export Database' feature.\n`);
    console.log(`Run command: \x1b[33mnode migrate.js <path_to_decrypted_file.json>\x1b[0m\n`);
    process.exit(1);
  }

  let dbData;
  try {
    const rawContent = fs.readFileSync(inputFilePath, 'utf8');
    dbData = JSON.parse(rawContent);
  } catch (e) {
    console.error(`\x1b[31mError: Failed to parse JSON file: ${e.message}\x1b[0m`);
    console.log(`Ensure the file is decrypted. (Verschlüsselte Dateien beginnen mit {"ciphertext":...} und müssen erst in der App exportiert werden.)`);
    process.exit(1);
  }

  // Verify structure
  const patientsList = dbData.patients || [];
  const woundsList = dbData.wounds || [];
  const entriesList = dbData.entries || [];
  
  // Custom body regions if saved in localstorage (we will also read regions if they exist in localStorage key or exported schema)
  const regionsList = dbData.regions || [];

  let sqlOutput = `-- =====================================================================\n`;
  sqlOutput += `-- WoundCarePro - Autogenerated Sync Data Import Dump\n`;
  sqlOutput += `-- DateTime: ${new Date().toISOString()}\n`;
  sqlOutput += `-- Source: ${inputFilePath}\n`;
  sqlOutput += `-- =====================================================================\n\n`;
  sqlOutput += `USE wound_care_pro;\n\n`;
  sqlOutput += `SET FOREIGN_KEY_CHECKS = 0;\n`;
  sqlOutput += `START TRANSACTION;\n\n`;

  // Clear existing records to allow re-runs of sync imports safely
  sqlOutput += `-- Clear existing tables\n`;
  sqlOutput += `TRUNCATE TABLE assessments;\n`;
  sqlOutput += `TRUNCATE TABLE wounds;\n`;
  sqlOutput += `TRUNCATE TABLE patients;\n\n`;

  // 1. Process Patients
  console.log(`Processing ${patientsList.length} patients...`);
  if (patientsList.length > 0) {
    sqlOutput += `-- Exporting PATIENTS\n`;
    patientsList.forEach(p => {
      sqlOutput += `INSERT INTO patients (id, name, dob, mrn, created_at) VALUES (\n  `;
      sqlOutput += `${sqlVal(p.id)}, ${sqlVal(p.name)}, ${sqlVal(p.dob)}, ${sqlVal(p.mrn)}, ${sqlDate(p.createdAt)}\n);\n`;
    });
    sqlOutput += `\n`;
  }

  // 2. Process Wounds
  console.log(`Processing ${woundsList.length} wounds...`);
  if (woundsList.length > 0) {
    sqlOutput += `-- Exporting WOUNDS\n`;
    woundsList.forEach(w => {
      sqlOutput += `INSERT INTO wounds (id, patient_id, location_name, x, y, view, status, created_at) VALUES (\n  `;
      sqlOutput += `${sqlVal(w.id)}, ${sqlVal(w.patientId)}, ${sqlVal(w.locationName)}, ${sqlVal(w.x)}, ${sqlVal(w.y)}, ${sqlVal(w.view)}, ${sqlVal(w.status)}, ${sqlDate(w.createdAt)}\n);\n`;
    });
    sqlOutput += `\n`;
  }

  // 3. Process Assessments (Entries)
  console.log(`Processing ${entriesList.length} assessments...`);
  if (entriesList.length > 0) {
    sqlOutput += `-- Exporting ASSESSMENTS / WOUND HISTORY\n`;
    entriesList.forEach(e => {
      sqlOutput += `INSERT INTO assessments (\n  `;
      sqlOutput += `id, wound_id, patient_id, author_id, length, width, depth, edges, phase, \n  `;
      sqlOutput += `exudate_amount, exudate_type, surroundings, cleanser, filler, dressing, \n  `;
      sqlOutput += `compression, compression_type, frequency, subjective_complaints, notes, image_url, created_at\n) VALUES (\n  `;
      
      sqlOutput += `${sqlVal(e.id)},\n  `;
      sqlOutput += `${sqlVal(e.woundId)},\n  `;
      sqlOutput += `${sqlVal(e.patientId)},\n  `;
      sqlOutput += `${sqlVal(e.authorId)},\n  `;
      
      sqlOutput += `${sqlVal(e.length)},\n  `;
      sqlOutput += `${sqlVal(e.width)},\n  `;
      sqlOutput += `${sqlVal(e.depth)},\n  `;
      
      sqlOutput += `${sqlVal(e.edges)},\n  `;
      sqlOutput += `${sqlVal(e.phase)},\n  `;
      sqlOutput += `${sqlVal(e.exudateAmount)},\n  `;
      sqlOutput += `${sqlVal(e.exudateType)},\n  `;
      sqlOutput += `${sqlVal(e.surroundings)},\n  `;
      
      sqlOutput += `${sqlVal(e.cleanser)},\n  `;
      sqlOutput += `${sqlVal(e.filler)},\n  `;
      sqlOutput += `${sqlVal(e.dressing)},\n  `;
      sqlOutput += `${sqlVal(e.compression)},\n  `;
      sqlOutput += `${sqlVal(e.compressionType)},\n  `;
      sqlOutput += `${sqlVal(e.frequency)},\n  `;
      
      sqlOutput += `${sqlVal(e.subjectiveComplaints)},\n  `;
      sqlOutput += `${sqlVal(e.notes)},\n  `;
      sqlOutput += `${sqlVal(e.imageUrl)},\n  `;
      sqlOutput += `${sqlDate(e.createdAt)}\n);\n\n`;
    });
  }

  // 4. Process custom body regions if exported
  if (regionsList.length > 0) {
    console.log(`Processing ${regionsList.length} customized body regions...`);
    sqlOutput += `-- Exporting CUSTOM BODY REGIONS\n`;
    sqlOutput += `TRUNCATE TABLE body_regions;\n`;
    regionsList.forEach(r => {
      sqlOutput += `INSERT INTO body_regions (id, name, view, cx, cy, r, type) VALUES (\n  `;
      sqlOutput += `${sqlVal(r.id)}, ${sqlVal(r.name)}, ${sqlVal(r.view)}, ${sqlVal(r.cx)}, ${sqlVal(r.cy)}, ${sqlVal(r.r)}, ${sqlVal(r.type || 'circle')}\n);\n`;
    });
    sqlOutput += `\n`;
  }

  sqlOutput += `COMMIT;\n`;
  sqlOutput += `SET FOREIGN_KEY_CHECKS = 1;\n`;

  try {
    fs.writeFileSync(outputFilePath, sqlOutput, 'utf8');
    console.log(`\n\x1b[32m✔ Success! Compiled SQL Dump written to: ${outputFilePath}\x1b[0m`);
    console.log(`Import options for Synology MariaDB 10 / Docker MariaDB:`);
    console.log(`1. Terminal: mysql -u <user> -p wound_care_pro < import.sql`);
    console.log(`2. GUI: Import 'import.sql' within phpMyAdmin, DBeaver, or Synology DB managers.`);
  } catch (e) {
    console.error(`\x1b[31mError writing output: ${e.message}\x1b[0m`);
  }
};

runMigration();
